baseURL = "https://johnsiu.com"
theme   = "sk3"
title   = "John Siu Blog"

DefaultContentLanguage = "en"
enableEmoji            = true
enableGitInfo          = true
enableInlineShortcodes = true
languageCode           = "en-us"

[pagination]
pagerSize = 24

[services]
[services.disqus]
shortname = "https-johnsiu-com"
[services.googleAnalytics]
id = "G-989EXZE534"

[author]
name = "John Siu"

[Params]
#custom_js           = ["/js/my.js"]
description          = "John Siu technology blog."
enableExternalSvg    = false
enableInfoBox        = true
enableListLastModify = true
enableOpenGraph      = true
enableOpenToc        = true
enableTwitterCard    = true
enableUserCanonical  = true
favicon              = "/favicon.ico"
mainSections         = "blog"
startdate            = "2012-12-02"
subtitle             = "Tech - Business Tool, Personal Toys"
title                = "John Siu Blog"

[Params.paypal]
# amount          = "5"
businessId      = "HZF49NM9D35SJ"
currency        = "CAD"
enableRecurring = true

[Params.google]
AdsenseId         = "ca-pub-8176479711832264"
enablePageLevelAd = true

[Params.sociallink]
#instagram      = "john.sd.siu"
#pinterest      = "johnsdsiu"
#tumblr         = "jsds"
#vimeo          = "user88929197"
#youtubechannel = "UC5LvdqfL2PubOp904UnUJAg"
#youtubeuser    = "JohnSDSiu"
facebook       = "john.siu.714"
flickr         = "johnsiu-com"
github         = "J-Siu"
linkedin       = "john-sing-dao-siu"
reddit         = "js1943"
rss            = true
stack-exchange = "1882213"
stack-overflow = "1810391"
twitter        = "JohnSiuCom"

[Params.socialshare]
facebook  = true
instagram = true
linkedin  = true
pinterest = true
reddit    = true
telegram  = true
twitter   = true
vk        = true

[Params.card]
date    = true
summary = true
#width   = "100%"

[Params.color]
bg     = "#181a1b"
border = "#f2f2f2"
link   = "#44a2ff"
text   = "white"

[menu]
[[menu.main]]
name = "Cheat Sheet"
url  = "/tags/cheatsheet/"
[[menu.main]]
name = "Tags"
url  = "/tags"
[[menu.main]]
name = "Links"
url  = "/home/links/"
[[menu.main]]
name = "About"
url  = "/home/about/"
[[menu.main]]
name = "Lib"
url  = "/tags/lib/"
[[menu.main]]
name = "Search"
url  = "/home/search/"
[[menu.main]]
name = "My IP"
url  = "/home/myip/"
[[menu.main]]
name = "Nslookup"
url  = "/home/nslookup/"
[[menu.main]]
name = "Privacy Policy"
url  = "/privacy_policy/"
[[menu.main]]
name = "Project"
url  = "/project/"

[markup]
defaultMarkdownHandler = "goldmark"

[markup.highlight]
codeFences         = true
guessSyntax        = false
hl_Lines           = ""
lineNoStart        = 1
lineNos            = true
lineNumbersInTable = true
noClasses          = true
style              = "rrt"
tabWidth           = 4

[markup.tableOfContents]
endLevel   = 6
ordered    = false
startLevel = 3

[markup.goldmark]
[markup.goldmark.extensions]
definitionList = true
footnote       = true
linkify        = true
strikethrough  = true
table          = true
taskList       = true
typographer    = true
[markup.goldmark.parser]
attribute         = true
autoHeadingID     = true
autoHeadingIDType = "github"
[markup.goldmark.renderer]
hardWraps = false
unsafe    = true
xhtml     = false

[outputs]
home = ["HTML", "RSS"]
