baseURL = "https://johnsiu.com"
title = "[JS Blog: Tech - Business Tool, Personal Toys]"

theme = "Binario"
languageCode = "en-us"
paginate = "24"
paginatepath = "blog"
tag_dir = "tag"
pluralizeListTitles=false

pygmentsCodefences=true
pygmentsStyle="Chroma"

googleAnalytics = "UA-36805525-1" # optional
disqusShortname = "https-johnsiu-com"

[Author] # Used in authorbox
  name = "John Siu"
  bio = ""
  avatar = ""

[Params]
  description = "Tech - Business Tool, Personal Toys" # Site Description. Used in meta description
  #copyright = "" # Copyright holder, otherwise will use .Site.Title
  opengraph = true # Enable OpenGraph if true
  twitter_cards = true # Enable Twitter Cards if true
  columns = 3 # Set the number of cards columns. Possible values: 1, 2, 3
  mainSections = ["blog"] # Set main page sections
  post_meta = ["date", "categories"] # Enable post meta fields in given order
  dateFormat = "January 02, 2006" # Change the format of dates
  colorTheme = "" # dark-green, dark-blue, dark-red, dark-violet
  customCSS = ["css/custom.css"] # Include custom CSS files
  mainMenuAlignment = "right" # Align main menu (desktop version) to the right side
  authorbox = true # Show authorbox at bottom of single pages if true
  toc = true # Enable Table of Contents for all site pages
  tocOpen = true # Open Table of Contents block. Optional
  comments = true # Enable comments for all site pages
  related = true # Enable Related content for single pages
  relatedMax = 5 # Set the maximum number of posts that can be displayed in related block. Optional
  mathjax = false # Enable MathJax for all site pages
  mathjaxPath = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/MathJax.js" # Specify MathJax path. Optional
  mathjaxConfig = "TeX-AMS-MML_HTMLorMML" # Specify MathJax config. Optional
  hideNoPostsWarning = false # Don't show no posts empty state warning in main page, if true

[Params.Social]
  #email = "example@example.com"
  #facebook = "username"
  twitter = "JohnSiuCom"
  #telegram = "username"
  #instagram = "username"
  #pinterest = "username"
  #vk = "username"
  linkedin = "john-sing-dao-siu"
  github = "J-Siu"
  #gitlab = "username"
  stackoverflow = "1810391"
  #mastodon = "username"
  #medium = "username"

[Params.Share] # Post Share block
  facebook = true
  twitter = true
  reddit = true
  telegram = true
  linkedin = true
  vk = true
  pocket = true

[Params.Adsense]
  ads_id = "ca-pub-8176479711832264"
	ads_auto = true
  ads_slot_top = "2063139251"
  ads_slot_bot = "1923538454"

# Web App Manifest settings
# https://www.w3.org/TR/appmanifest/
# https://developers.google.com/web/fundamentals/web-app-manifest/
[Params.Manifest]
  name = "John Siu"
  shortName = "JohnSiu"
  display = "browser"
  backgroundColor = "#2a2a2a"
  themeColor = "#1b1b1b"
  description = "Responsive card-based & code-light Hugo theme"
  orientation = "portrait"
  startUrl = "/"
  scope = "/"

[outputFormats]
  [outputFormats.MANIFEST]
    mediaType = "application/json"
    baseName = "manifest"
    isPlainText = true
    notAlternative = true

[outputs]
  home = ["HTML", "RSS", "MANIFEST"]

[permalinks]
  post = "/blog/:filename/"

[menu]
[[menu.main]]
name="[Cheat Sheet]"
url="/cheatsheet"