baseURL = "https://johnsiu.com"
theme   = "sk3"
title   = "John Siu Blog"

DefaultContentLanguage = "en"
enableGitInfo          = true
enableInlineShortcodes = true
languageCode           = "en"
paginate               = 24
#relativeURLs           = true

disqusShortname = "https-johnsiu-com"
googleAnalytics = "UA-36805525-1"

[Params]
maintype  = "blog"
pagewidth = "1200px"
startdate = "2012-12-02"
subtitle  = "Tech - Business Tool, Personal Toys"

adsense_id  = "ca-pub-8176479711832264"
description = "John Siu technology blog."
opengraph   = true
title       = "John Siu Blog"
twitercards = true

	[Params.sociallink]
	facebook       = "john.siu.714"
	flickr         = "johnsiu-com"
	instagram      = "john.sd.siu"
	linkedin       = "john-sing-dao-siu"
	pinterest      = "johnsdsiu"
	reddit         = "js1943"
	tumblr         = "jsds"
	twitter        = "JohnSiuCom"
	vimeo          = "user88929197"
	youtubechannel = "UC5LvdqfL2PubOp904UnUJAg"
	youtubeuser    = "JohnSDSiu"

	[Params.socialshare]
	facebook  = true
	instagram = true
	linkedin  = true
	pinterest = true
	reddit    = true
	telegram  = true
	twitter   = true
	vk        = true

	[Params.card]
	date    = true
	summary = true
	#width   = "100%"

	[Params.color]
	bg     = "#181a1b"
	border = "white"
	link   = "#3d84ff"
	text   = "white"

[menu]
	[[menu.main]]
	name = "Cheat Sheet"
	url  = "/tags/cheatsheet/"
	[[menu.main]]
	name = "Tags"
	url  = "/tags"
	[[menu.main]]
	name = "Links"
	url  = "/page/links/"
	[[menu.main]]
	name = "About"
	url  = "/page/about/"
	[[menu.main]]
	name = "Lib"
	url  = "/tags/lib/"
	[[menu.main]]
	name = "Search"
	url  = "/page/search/"

[markup]
	[markup.tableOfContents]
	endLevel   = 6
	startLevel = 3

[outputFormats]
	[outputFormats.MANIFEST]
	baseName       = "manifest"
	isPlainText    = true
	mediaType      = "application/json"
	notAlternative = true

[outputs]
home = ["HTML", "RSS", "MANIFEST"]

[Author] # Used in authorbox
bio  = "Minimize the Effort, Maximize the Effect!"
name = "John Siu"
