baseURL = "https://johnsiu.com"
title = "[JS Blog: Tech - Business Tool, Personal Toys]"

theme = "Binario"
languageCode = "en-us"
paginate = "24"
paginatepath = "blog"
enableGitInfo = true
pluralizeListTitles=false

#pygmentsCodefences=true
#pygmentsStyle="Chroma"

googleAnalytics = "UA-36805525-1" # optional
disqusShortname = "https-johnsiu-com"

[markup]
  [markup.tableOfContents]
    endLevel = 6
    startLevel = 1
  [markup.goldmark]
    [markup.goldmark.extensions]
      definitionList = true
      footnote = true
      linkify = true
      strikethrough = true
      table = true
      taskList = true
      typographer = true
    [markup.goldmark.parser]
      attribute = true
      autoHeadingID = true
    [markup.goldmark.renderer]
      hardWraps = false
      unsafe = true
      xHTML = false
  [markup.highlight]
    codeFences = true
    hl_Lines = ""
    lineNoStart = 1
    lineNos = true
    lineNumbersInTable = true
    noClasses = true
    style = "monokai"
    tabWidth = 4

[Author] # Used in authorbox
  name = "John Siu"
  bio = "Minimize the Effort, Maximize the Effect!"
  avatar = ""

[Params]
  #copyright = "" # Copyright holder, otherwise will use .Site.Title
  #mathjax = false # Enable MathJax for all site pages
  #mathjaxConfig = "TeX-AMS-MML_HTMLorMML" # Specify MathJax config. Optional
  #mathjaxPath = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/MathJax.js" # Specify MathJax path. Optional
  authorbox = true # Show authorbox at bottom of single pages if true
  colorTheme = "" # dark-green, dark-blue, dark-red, dark-violet
  columns = 3 # Set the number of cards columns. Possible values: 1, 2, 3
  comments = true # Enable comments for all site pages
  customCSS = ["css/custom.css"] # Include custom CSS files
  dateFormat = "January 02, 2006" # Change the format of dates
  description = "Tech - Business Tool, Personal Toys" # Site Description. Used in meta description
  hideNoPostsWarning = false # Don't show no posts empty state warning in main page, if true
  mainMenuAlignment = "right" # Align main menu (desktop version) to the right side
  mainSections = ["blog"] # Set main page sections
  opengraph = true # Enable OpenGraph if true
  post_meta = ["date", "categories"] # Enable post meta fields in given order
  related = true # Enable Related content for single pages
  relatedMax = 5 # Set the maximum number of posts that can be displayed in related block. Optional
  toc = true # Enable Table of Contents for all site pages
  tocOpen = true # Open Table of Contents block. Optional
  twitter_cards = true # Enable Twitter Cards if true
[Params.Social]
  #email = "example@example.com"
  #gitlab = "username"
  #instagram = "username"
  #mastodon = "username"
  #medium = "username"
  #pinterest = ""
  #telegram = "username"
  #vk = "username"
  facebook = "john.siu.714"
  github = "J-Siu"
  linkedin = "john-sing-dao-siu"
  stackoverflow = "1810391"
  twitter = "JohnSiuCom"

[Params.Share] # Post Share block
  facebook = true
  linkedin = true
  pocket = true
  reddit = true
  telegram = true
  twitter = true
  vk = true
	pinterest = true

[Params.Adsense]
  ads_id = "ca-pub-8176479711832264"
  ads_auto = true
  ads_slot_top = "2063139251"
  ads_slot_bot = "1923538454"

# Web App Manifest settings
# https://www.w3.org/TR/appmanifest/
# https://developers.google.com/web/fundamentals/web-app-manifest/
[Params.Manifest]
  name = "John Siu"
  shortName = "JohnSiu"
  display = "browser"
  backgroundColor = "#2a2a2a"
  themeColor = "#1b1b1b"
  description = "JS Blog: Tech - Business Tool, Personal Toys"
  orientation = "portrait"
  startUrl = "/"
  scope = "/"

[outputFormats]
  [outputFormats.MANIFEST]
    mediaType = "application/json"
    baseName = "manifest"
    isPlainText = true
    notAlternative = true

[outputs]
  home = ["HTML", "RSS", "MANIFEST"]

[permalinks]
  post = "/blog/:filename/"

[menu]
  [[menu.main]]
    name="Cheat Sheet"
    url="/tags/cheatsheet/"
  [[menu.main]]
    name="Tags"
    url="/tags"
  [[menu.main]]
    name="Links"
    url="/page/links/"
  [[menu.main]]
    name="About"
    url="/page/about/"
  [[menu.main]]
    name="Lib"
    url="/tags/lib/"
  [[menu.main]]
    name="Search"
    url="/page/search/"
